version: "3.7"

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER:     ${DB_USER}
            POSTGRES_DB:       ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    adminer:
        image: adminer
        depends_on: 
            - "db"
        ports:
            - 8081:8080